using BankDB;
using DataTierWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace DataTierWeb.Controllers
{
    
    public class CreateAccountController : ApiController
    {
        //cretaing object of bandBD.dll
        public static BankDB.BankDB Instance { get; } = new BankDB.BankDB();

        //To access the functions provided under user and AccountAccessInterfaces respectively
        private static UserAccessInterface user = Instance.GetUserAccess();
        private static AccountAccessInterface account = Instance.GetAccountInterface();


        // POST: api/CreateAccount
        public uint Post([FromBody]AccountModel value)
        {
            //selecting the user by passing userID, and creating a new account for the respective user.
            uint accID = 0;
            user.SelectUser(value.userId);
            try
            {
                //saving the generated account ID
                accID = account.CreateAccount(value.userId);
                Instance.SaveToDisk();
            }
            catch (Exception e)
            {
                Console.WriteLine("Cannot create account: " + e);
            }
            //returning the accountID
            return accID;
        }






        //all the other autogenerated code which are not used in this project
        /*

        // GET: api/CreateAccount
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/CreateAccount/5
        public string Get(int id)
        {
            return "value";
        }
        // PUT: api/CreateAccount/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/CreateAccount/5
        public void Delete(int id)
        {
        }
        */
    }
}
