using BankDB;
using DataTierWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace DataTierWeb.Controllers
{
    public class GetAccountInfoController : ApiController
    {
        public static BankDB.BankDB Instance { get; } = new BankDB.BankDB();

        //To access the functions provided under AccountAccessInterfaces
        private static AccountAccessInterface account = Instance.GetAccountInterface();
    

        // POST: api/GetAccountInfo
        public List<uint> Post([FromBody]AccountModel value)
        {
            List<uint> accList = new List<uint>();
            try
            {
                //retrieving all the accounts of the selected user and storeing them in a list
                accList = account.GetAccountIDsByUser(value.userId);
            }
            catch (Exception e)
            {
                Console.WriteLine("Cannot get accounts of the user: " + e);
            }
            //returning list of accounts
            return accList;
        }





        //all the other autogenerated code which are not used in this project
        /*

        // GET: api/GetAccountInfo
        public string Get()
        {

            return "value";
        }

        // GET: api/GetAccountInfo/5
        public string Get(int id)
        {
            return "value";
        }

        // PUT: api/GetAccountInfo/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/GetAccountInfo/5
        public void Delete(int id)
        {
        }*/
    }
}
