using BankDB;
using DataTierWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace DataTierWeb.Controllers
{
    public class GetAccountBalanceController : ApiController
    {
        public static BankDB.BankDB Instance { get; } = new BankDB.BankDB();

        //To access the functions provided under AccountAccessInterfaces
        private static AccountAccessInterface account = Instance.GetAccountInterface();

  
        // POST: api/GetAccountBalance
        public uint Post([FromBody]AccountModel value)
        {
            uint balance = 0;
            try
            {
                //getiing balance of selected account
                account.SelectAccount(value.id);
                balance = account.GetBalance();
            }

            catch (Exception e)
            {
                Console.WriteLine("Cannot deposit: " + e);
            }

            return balance;
        }


        //all the other autogenerated codes which are not used in this project

        /*
        // GET: api/GetAccountBalance
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/GetAccountBalance/5
        public string Get(int id)
        {
            return "value";
        }

        // PUT: api/GetAccountBalance/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/GetAccountBalance/5
        public void Delete(int id)
        {
        }*/
    }
}
