using BankDB;
using DataTierWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace DataTierWeb.Controllers
{
    public class GetRespectiveAccountController : ApiController
    {
        public static BankDB.BankDB Instance { get; } = new BankDB.BankDB();

        //To access the functions provided under Transacgtion and AccountAccessInterfaces respectively
        private static TransactionAccessInterface trans = Instance.GetTransactionInterface();
        private static AccountAccessInterface account = Instance.GetAccountInterface();
    

        // POST: api/GetRespectiveAccount
        public uint[] Post([FromBody]TransactionModel value)
        {
            //processing all transactions
            Instance.ProcessAllTransactions();
            uint[] output = new uint[2];
            uint id = value.id;

            //getting sender and receiver account details from the selected transaction id
            trans.SelectTransaction(value.id);
            output[0] = trans.GetSendrAcct();
            output[1] = trans.GetRecvrAcct();

            return output;
        }


        //all the otehr autogenerated codes which are not used in this project


        // GET: api/GetSenderAccount
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/GetSenderAccount/5
        public string Get(int id)
        {
            return "value";
        }
        // PUT: api/GetSenderAccount/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/GetSenderAccount/5
        public void Delete(int id)
        {
        }
    }
}
