using BankDB;
using DataTierWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.ServiceModel;
using System.Web.Http;

namespace DataTierWeb.Controllers
{
    public class GetUserDetailsController : ApiController
    {
        public static BankDB.BankDB Instance { get; } = new BankDB.BankDB();

        //To access the functions provided under userAccessInterfaces
        private static UserAccessInterface user = Instance.GetUserAccess();


        // GET: api/GetUserDetails
        public List<uint> Get()
        {
            //return list of all user ids....
            List<uint> usersList = user.GetUsers();
            return usersList;
        }



        // POST: api/GetUserDetails
        public string[] Post([FromBody]UsersModel value)
        {
           string fname = null;
           string lname = null;
           string[] output = new string[2];

            try
            {
                //retrieving firstname and lastname of the sleected user and storeing them in an array
                user.SelectUser(value.id);
                user.GetUserName(out fname, out lname);
                output[0] = fname;
                output[1] = lname;
            }
            catch (FaultException e)
            {
                Console.WriteLine("Cannot retreive user details: " + e);
            }

            return output;
        }

        //all the other autogenerated codes which are not used

        // GET: api/GetUserDetails/5
        public void Get(uint id)
        {


        }
        // PUT: api/GetUserDetails/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/GetUserDetails/5
        public void Delete(int id)
        {
        }
    }
}
