using BankDB;
using DataTierWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.ServiceModel;
using System.Web.Http;

namespace DataTierWeb.Controllers
{
    public class TransactionController : ApiController
    {
        public static BankDB.BankDB Instance { get; } = new BankDB.BankDB();

        //To access the functions provided under Transaction and AccountAccessInterfaces respectively
        private static TransactionAccessInterface trans = Instance.GetTransactionInterface();
        private static AccountAccessInterface account = Instance.GetAccountInterface();



        // GET: api/Transaction
        public List<uint> Get()
        {
            //to get the list of all the transaction ids.
            List<uint> transactionList = trans.GetTransactions();
            return transactionList;
            
        }

 


        // POST: api/Transaction
        public uint[] Post([FromBody] TransactionModel value)
        {
            uint transID = 0;
            uint balance = 0;

            uint[] output = new uint[4];
        
   
            try
            {
                //creating a new transaction and selecting it to set sender and receiveer's account ids
                transID = trans.CreateTransaction();

                trans.SelectTransaction(transID);

                trans.SetAmount(value.amount);
                trans.SetSendr(value.sender);
                trans.SetRecvr(value.receiver);
                account.SelectAccount(value.sender);
                //selecting account of the senders and retirving balance of the semders account
                balance = account.GetBalance();

            }
            catch (Exception e)
            {
                Console.WriteLine("Cannot proceed with transaction " + e);
            }
            output[0] = transID;
            output[1] = balance;

            return output;
        
        }

        //all the other autogenerated codes which are not used
        /*
        // GET: api/Transaction/5
        public string Get(int id)
        {
            return "value";
        }

        // PUT: api/Transaction/5
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE: api/Transaction/5
        public void Delete(int id)
        {
        }*/
    }
}
